services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: "redis:alpine"

  web:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      USE_STUB_DATA: ${USE_STUB_DATA}

  celery_worker:
    build:
      context: ./app
      dockerfile: Dockerfile.celery
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      USE_STUB_DATA: ${USE_STUB_DATA}
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
